[package]
name = "webrtc-server"
version = "0.1.0"
authors = ["cheme <emericchevalier.pro@gmail.com>"]

[dependencies]
hyper="~0.11.22"
futures="~0.1.18"
tokio-core="*"
websocket = "~0.20.2"
tk-listen= "*"
dotenv = "*"
dotenv_codegen = "*"
mime = "~0.3.5"
